version: "3.5"

services:
  php:
    container_name: "desafio.php"
    build: docker/php
    volumes:
      - ./app:/var/www/html
    networks:
      - desafio-network

  nginx:
    container_name: "desafio.nginx"
    build: docker/nginx
    volumes:
      - ./app:/var/www/html
    ports:
      - "80:80"
    networks:
      - desafio-network

  database:
    container_name: "desafio.database"
    image: mysql:8
    volumes:
      - /.dbdata:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: desafio
    networks:
      - desafio-network

networks:
  desafio-network:
    driver: "bridge"
